name: Sync to Gitee

on:
  push:
    branches: [main, dev, build, gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 在 Settings->Secrets
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          # GitHub 源仓库地址
          source-repo: git@github.com:vangleer/vangle.git
          # Gitee 目标仓库地址
          destination-repo: git@gitee.com:vangleer/vangle.git
